---
abstract: 'Perl bindings for a Neo4j graph database'
author:
  - 'Mark A. Jensen'
build_requires:
  List::MoreUtils: 0
  Module::Build: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: REST-Neo4p
provides:
  REST::Neo4p:
    file: lib/REST/Neo4p.pm
    version: 0.2120
  REST::Neo4p::Agent:
    file: lib/REST/Neo4p/Agent.pm
    version: 0.2110
  REST::Neo4p::Batch:
    file: lib/REST/Neo4p/Batch.pm
    version: 0.2001
  REST::Neo4p::Constrain:
    file: lib/REST/Neo4p/Constrain.pm
    version: 0.2002
  REST::Neo4p::Constraint:
    file: lib/REST/Neo4p/Constraint.pm
    version: 0.2001
  REST::Neo4p::Constraint::NodeProperty:
    file: lib/REST/Neo4p/Constraint/Property.pm
    version: 0
  REST::Neo4p::Constraint::Property:
    file: lib/REST/Neo4p/Constraint/Property.pm
    version: 0.20
  REST::Neo4p::Constraint::Relationship:
    file: lib/REST/Neo4p/Constraint/Relationship.pm
    version: 0.2001
  REST::Neo4p::Constraint::RelationshipProperty:
    file: lib/REST/Neo4p/Constraint/Property.pm
    version: 0
  REST::Neo4p::Constraint::RelationshipType:
    file: lib/REST/Neo4p/Constraint/RelationshipType.pm
    version: 0.2001
  REST::Neo4p::Entity:
    file: lib/REST/Neo4p/Entity.pm
    version: 0.2001
  REST::Neo4p::Exceptions:
    file: lib/REST/Neo4p/Exceptions.pm
    version: 0.2020
  REST::Neo4p::Index:
    file: lib/REST/Neo4p/Index.pm
    version: 0.2111
  REST::Neo4p::Node:
    file: lib/REST/Neo4p/Node.pm
    version: 0.2120
  REST::Neo4p::Path:
    file: lib/REST/Neo4p/Path.pm
    version: 0.2120
  REST::Neo4p::Query:
    file: lib/REST/Neo4p/Query.pm
    version: 0.2114
  REST::Neo4p::Relationship:
    file: lib/REST/Neo4p/Relationship.pm
    version: 0.2120
requires:
  Exception::Class: 1.3
  JSON: 2
  JSON::Streaming::Reader: 0.05
  LWP::UserAgent: 6.04
  URI::Escape: 3.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.2120
